

List pledge = [
  "doit chanter en prenant un objet comme guise de micro",
  "Faire un tatouage (que vous aurez choisi) sur une partie du corps",
  "doit danser un slow avec toi",
  "doit marcher une dizaine de mètres avec un objet en équilibre sur la tête sans le faire tomber",
  "doit jouer à la marelle avec toi",
  "doit imiter la gestuelle d'un animal",
  "doit tenir un balai en équilibre sur sa main pendant au moins quinze secondes",
  "doit porter ton verre pendant que tu lui parles",
  "Lui servir un verre trois fois de suite, il faut qu’elle ou ils les boivent",
  "Lui demander de raconter une blague et ne pas rire",
  "doit te montrer une photo de lui/elle plus jeune (permis de conduire,...)",
  "L'aider à réussir sa mission",
  "Le ou la convaincre de t'aider à réussir ta mission",
  "boire dans ton verre",
  "doit boire dans le verre d'un autre (mais pas le tien)",
  "doit faire un combat de pouce avec toi",
  "doit faire un bras de fer avec toi",
  "doit parler une autre langue (quelques secondes suffiront)",
  "Tu dois la/le faire répéter 3 fois de suite",
  "doit boire son verre cul sec",
  "Recevoir une déclaration d'amour ou d'amitié de sa part",
  "doit embrasser quelqu'un",
  "doit se déguiser pour une photo",
  "doit finir une de tes phrases",
  "doit jouer une scène de film culte",
  "doit chanter une chanson dans une autre langue",
  "doit danser avec toi pendant la soirée",
  "doit serrer la mais à au moins 10 personnes (après avoir dit bonjour évidemment)",
  "doit jouer d'un instrument de musique (ps: il y a une guitar dans ma chambre si tu veux)",
  "doit ouvrir une bière sans décapsuleur",
  "doit faire une battle de dance avec toi",
  "doit manger de la pomme au Ketchup: votre dernière belle sensation culinaire!",
  "doit faire au moins trois jongles avec un ballon, une chaussette ou tout autre objets.",
  "doit changer de place au moins 2 fois au cours du repas",
  "doit un selfie avec vous",
  "doit chanter la Marseillaise",
  "doit rigoler réellement à l'une de tes histoire drôle (un sourire courtois ne compte pas).",
  "doit de faire 2 compliements",
];